server.port=8081

# ==========================================
# CONFIGURACION DE ORACLE CLOUD (WALLET)
# ==========================================
spring.datasource.url=jdbc:oracle:thin:@nbr0lpwalzyse8ch_high?TNS_ADMIN=./src/main/resources/WALLET
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.username=ADMIN

# 2. Contraseña con la que creaste la base de datos en Oracle
spring.datasource.password=Renemaria1234

# Configuracion de JPA / Hibernate para Oracle
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ==========================================
# CONFIGURACION DE RABBITMQ (CONSUMIDOR)
# ==========================================
# Para tus pruebas locales individuales usa localhost.
# Al integrarse con Maria, aqui ira la IP de su maquina o el host comun.
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Nombre de la cola acordada que vas a escuchar
duoc.queue.name=inscripciones.queue